export const REQUEST_POKEMON_LIST = 'REQUEST_POKEMON_LIST';
export const RECEIVE_POKEMON_LIST = 'RECEIVE_POKEMON_LIST';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const REQUEST_SELECT_POKEMON = 'REQUEST_SELECT_POKEMON';
export const RECEIVE_SELECT_POKEMON = 'RECEIVE_SELECT_POKEMON';
export const ISLOADING_POKEMON = 'ISLOADING_POKEMON';
export const REMOVE_POKEMON = 'REMOVE_POKEMON';
